// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const footerContainer: string;
export const footerSns: string;
export const footerMenu: string;
export const footerSite: string;
