// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const headerContainer: string;
export const navBtn: string;
export const faBars: string;
export const faTimes: string;
export const open: string;
export const nav: string;
