// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const body: string;
export const wContainer: string;
export const header: string;
export const headerContainer: string;
export const navBtn: string;
