// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const body: string;
export const wContainer: string;
export const btn: string;
export const header: string;
export const headerContainer: string;
export const navBtn: string;
export const hero: string;
export const heroContainer: string;
export const imgText: string;
export const imgTextContainer: string;
export const headingDecoration: string;
export const text: string;
export const img: string;
export const reverse: string;
export const posts: string;
export const heading: string;
