// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const globalNav: string;
export const siteNav: string;
export const navItem: string;
export const check: string;
export const drawerMenu: string;
export const drawerList: string;
export const drawerItem: string;
export const drawerLink: string;
export const menuBtn: string;
export const bar: string;
export const barTop: string;
export const barMiddle: string;
export const barBottom: string;
