// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const details: string;
export const summary: string;
export const technologies: string;
export const fadeIn: string;
export const title: string;
