// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const card: string;
export const percent: string;
export const dot: string;
export const animateDot: string;
export const svg: string;
export const fadeIn: string;
export const number: string;
export const show: string;
export const text: string;
export const sa: string;
export const saUp: string;
