// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const button: string;
export const wrapper: string;
export const headerTitle: string;
export const headerSubTitle: string;
export const text: string;
export const mySkill: string;
export const topToDown: string;
export const message: string;
export const time: string;
export const arrowContainer: string;
export const arrow: string;
export const arrowMove: string;
export const sa: string;
export const show: string;
export const saUp: string;
