// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const sectionTitle: string;
export const sectionWrapper: string;
export const imgWrapper: string;
export const sec5: string;
export const footer: string;
export const footerTitle: string;
export const sa: string;
export const show: string;
export const saUp: string;
export const gradient: string;
