// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const linkItem: string;
export const linkTitle: string;
export const icon: string;
export const text: string;
