// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const siteTitle: string;
export const globalNav: string;
export const navItem: string;
export const wrapper: string;
export const main: string;
export const hotTopic: string;
export const topic: string;
export const content: string;
export const title: string;
export const desc: string;
export const date: string;
export const sideMenu: string;
export const footer: string;
